spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ywhc_admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}

# 生产环境日志配置
logging:
  level:
    root: warn
    com.ywhc.admin: info
    org.springframework.security: warn
  file:
    name: logs/ywhc-admin-prod.log
    max-size: 100MB
    max-history: 30

# JWT配置 - 生产环境
jwt:
  secret: ${JWT_SECRET:ywhc-admin-prod-secret-key-2024-change-in-production}
  expiration: 7200000 # 2小时
  refresh-expiration: 604800000 # 7天
  token-prefix: "Bearer "

# Knife4j配置 - 生产环境
knife4j:
  enable: false
  production: true
