spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ywhc_admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: zsb
      database: 0

# 开发环境日志配置
logging:
  level:
    root: info
    com.ywhc.admin: debug
    org.springframework.security: debug
    com.baomidou.mybatisplus: debug
  file:
    name: logs/ywhc-admin-dev.log

# JWT配置 - 开发环境
jwt:
  secret: ywhc-admin-secret-key-2024-very-long-secret-key-for-security-must-be-at-least-32-bytes
  expiration: 86400000 # 24小时
  refresh-expiration: 604800000 # 7天

# Knife4j配置 - 开发环境
knife4j:
  enable: true
  production: false
