spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ywhc_admin}?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PWD:zsb}
      database: ${REDIS_DB:0}

# 开发环境日志配置
logging:
  level:
    root: info
    com.ywhc.admin: debug
    org.springframework.security: debug
    com.baomidou.mybatisplus: debug
  file:
    name: logs/ywhc-admin-dev.log

# JWT配置 - 开发环境
jwt:
  secret: ywhc-admin-secret-key-2024-very-long-secret-key-for-security-must-be-at-least-32-bytes
  expiration: 86400000 # 24小时
  refresh-expiration: 604800000 # 7天
  token-prefix: "Bearer "

# Knife4j配置 - 开发环境
knife4j:
  enable: true
  production: false
